# Generated by Django 5.0.2 on 2024-05-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='songs',
        ),
        migrations.AlterField(
            model_name='artist',
            name='monthly_listeners',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(null=True),
        ),
    ]
